import { useMemo, useState } from "react";
import { Cake, CalendarDays, Check, Heart, Lightbulb, MessageCircle, Plus, Search, Sparkles, Users, Vote } from "lucide-react";
import { createCollab, createIdea, createMeetup, getCollabs, getIdeas, getIntroductions, getMeetups, getProfiles, getSupporters, saveIntroduction, startSupportCheckout, toggleIdeaVote, updateProfile, uploadAvatar } from "../lib/data";
import { useLoader } from "../lib/hooks";
import { Avatar, Empty, ErrorState, Field, Loading, Modal, PageHeader, formatDate } from "../components/ui";

function SubmitModal({ kind, onClose, onSaved, user, profile }) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{
    if(kind==="idea") await createIdea(user,profile,{title:form.get("title"),description:form.get("description")});
    if(kind==="collab") await createCollab(user.id,{title:form.get("title"),description:form.get("description"),category:form.get("category"),looking_for:form.get("looking_for")});
    if(kind==="meetup") await createMeetup(user.id,{meetup_date:form.get("date"),start_time:form.get("time"),duration:Number(form.get("duration")),message:form.get("message"),vrc_username:form.get("vrc"),meetup_type:form.get("type"),additional_participants:0,time_flexibility:"Exact"});
    onSaved();onClose();
  }catch(e){setError(e.message)}finally{setBusy(false)}}
  const labels={idea:"Share an idea",collab:"Create a collaboration",meetup:"Request a meetup"};
  return <Modal title={labels[kind]} onClose={onClose}><form className="stack-form" onSubmit={submit}>
    {kind!=="meetup"&&<Field label="Title"><input name="title" maxLength="120" required/></Field>}
    {kind==="collab"&&<><Field label="Category"><select name="category"><option>Creative</option><option>Gaming</option><option>Development</option><option>Events</option><option>Other</option></select></Field><Field label="Looking for"><input name="looking_for" placeholder="Artists, testers, hosts…" required/></Field></>}
    {kind==="meetup"&&<div className="form-grid"><Field label="Date"><input name="date" type="date" required/></Field><Field label="Start time"><input name="time" type="time" required/></Field><Field label="Duration"><select name="duration"><option value="30">30 minutes</option><option value="60">1 hour</option><option value="90">90 minutes</option><option value="120">2 hours</option></select></Field><Field label="Meetup type"><select name="type"><option>VRChat</option><option>Game night</option><option>Hangout</option></select></Field><Field label="VRChat username"><input name="vrc" required/></Field></div>}
    <Field label={kind==="meetup"?"Message":"Description"}><textarea name={kind==="meetup"?"message":"description"} rows="5" maxLength="1800" required/></Field>
    {error&&<p className="form-message">{error}</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?"Sending…":"Publish"}</button></div>
  </form></Modal>;
}

export function IntroductionsPage({ user, profile }) {
  const {data,loading,error,reload}=useLoader(getIntroductions,[]); const [editing,setEditing]=useState(false); const mine=data?.find(i=>i.user_id===user.id);
  async function save(event){event.preventDefault();const f=new FormData(event.currentTarget);await saveIntroduction(user.id,{introduction:f.get("introduction"),games:f.get("games"),interests:f.get("interests"),working_on:f.get("working_on"),fun_fact:f.get("fun_fact")},mine?.id);setEditing(false);reload()}
  return <div className="page"><PageHeader eyebrow="Community" title="Crew introductions" description="Meet the people behind the usernames and find your next shared interest." action={<button className="button primary" onClick={()=>setEditing(true)}><Plus/> {mine?"Edit yours":"Introduce yourself"}</button>}/>
  {loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:<div className="card-grid introductions-grid">{data?.map(item=><article className="panel intro-card" key={item.id}><div className="card-person"><Avatar profile={item.profile}/><div><h3>{item.profile?.username||"Crew member"}</h3><span className="rank">{item.profile?.rank||"Crew"}</span></div></div><p className="card-copy">{item.introduction}</p><div className="tag-row">{item.games&&<span>🎮 {item.games}</span>}{item.interests&&<span>✨ {item.interests}</span>}</div>{item.working_on&&<p className="micro-copy"><strong>Working on:</strong> {item.working_on}</p>}{item.fun_fact&&<p className="micro-copy"><strong>Fun fact:</strong> {item.fun_fact}</p>}</article>)}</div>}
  {editing&&<Modal title="Your introduction" onClose={()=>setEditing(false)}><form className="stack-form" onSubmit={save}><Field label="About you"><textarea name="introduction" rows="5" defaultValue={mine?.introduction} required/></Field><Field label="Games"><input name="games" defaultValue={mine?.games}/></Field><Field label="Interests"><input name="interests" defaultValue={mine?.interests}/></Field><Field label="What are you working on?"><input name="working_on" defaultValue={mine?.working_on}/></Field><Field label="Fun fact"><input name="fun_fact" defaultValue={mine?.fun_fact}/></Field><button className="button primary">Save introduction</button></form></Modal>}</div>;
}

export function IdeasPage({user,profile}){const {data,loading,error,reload}=useLoader(getIdeas,[]);const[open,setOpen]=useState(false);async function vote(item){await toggleIdeaVote(item.id,user.id,item.votes.some(v=>v.user_id===user.id));reload()}
return <div className="page"><PageHeader eyebrow="Ideas board" title="Shape what comes next" description="Pitch improvements, vote on favorites, and follow ideas from spark to launch." action={<button className="button primary" onClick={()=>setOpen(true)}><Plus/>New idea</button>}/>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:<div className="feed">{data?.map(item=><article className="panel idea-card" key={item.id}><div className="vote-column"><button className={item.votes.some(v=>v.user_id===user.id)?"vote active":"vote"} onClick={()=>vote(item)}><Vote/><strong>{item.votes.length}</strong></button></div><div><div className="card-meta"><span className={`status ${String(item.status).toLowerCase().replaceAll(" ","-")}`}>{item.status}</span><span>{formatDate(item.created_at)}</span></div><h2>{item.title}</h2><p>{item.description}</p><small>Proposed by {item.username||"Crew member"}</small></div></article>)}</div>}{open&&<SubmitModal kind="idea" user={user} profile={profile} onClose={()=>setOpen(false)} onSaved={reload}/>}</div>}

export function CollabsPage({user,profile}){const{data,loading,error,reload}=useLoader(getCollabs,[]);const[open,setOpen]=useState(false);return <div className="page"><PageHeader eyebrow="Collab board" title="Build something together" description="Find the missing skill, teammate, or creative spark for your next project." action={<button className="button primary" onClick={()=>setOpen(true)}><Plus/>Post collaboration</button>}/>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:<div className="card-grid">{data?.map(item=><article className="panel collab-card" key={item.id}><div className="card-meta"><span className="status open">{item.status}</span><span>{item.category}</span></div><h2>{item.title}</h2><p>{item.description}</p><div className="looking-for"><Users/><span><small>Looking for</small><strong>{item.looking_for}</strong></span></div><div className="card-person compact"><Avatar profile={item.profile} size={34}/><span>{item.profile?.username||"Crew member"}</span></div></article>)}</div>}{open&&<SubmitModal kind="collab" user={user} profile={profile} onClose={()=>setOpen(false)} onSaved={reload}/>}</div>}

export function CrewPage({onMessage}){const{data,loading,error,reload}=useLoader(()=>getProfiles(),[]);const[q,setQ]=useState("");const filtered=useMemo(()=>(data||[]).filter(p=>p.username?.toLowerCase().includes(q.toLowerCase())),[data,q]);return <div className="page"><PageHeader eyebrow="Crew directory" title="Everyone in orbit" description="Browse community members, see who is around, and start a conversation." action={<div className="search-box"><Search/><input placeholder="Search crew" value={q} onChange={e=>setQ(e.target.value)}/></div>}/>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:<div className="crew-grid">{filtered.map(person=><article className="panel crew-card" key={person.id}><div className={`presence ${person.online?"online":""}`}/><Avatar profile={person} size={72}/><h3>{person.username}</h3><span className="rank">{person.rank||"Crew"}</span><p>{person.bio||person.favorite_game||"Exploring the community."}</p><button className="button secondary" onClick={()=>onMessage(person)}><MessageCircle/>Message</button></article>)}</div>}</div>}

export function BirthdaysPage(){const{data,loading,error,reload}=useLoader(()=>getProfiles("id,username,avatar,birthday,show_birthday"),[]);const visible=(data||[]).filter(p=>p.birthday&&p.show_birthday).sort((a,b)=>{const now=new Date();const next=p=>{const d=new Date(p.birthday);let n=new Date(now.getFullYear(),d.getUTCMonth(),d.getUTCDate());if(n<new Date(now.toDateString()))n.setFullYear(n.getFullYear()+1);return n};return next(a)-next(b)});return <div className="page"><PageHeader eyebrow="Celebrations" title="Member birthdays" description="Never miss a chance to celebrate someone in the crew."/>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:visible.length?<div className="birthday-list">{visible.map(person=><article className="panel birthday-card" key={person.id}><div className="birthday-icon"><Cake/></div><Avatar profile={person}/><div><h3>{person.username}</h3><p>{new Intl.DateTimeFormat(undefined,{month:"long",day:"numeric",timeZone:"UTC"}).format(new Date(person.birthday))}</p></div></article>)}</div>:<Empty title="No shared birthdays yet" body="Birthdays appear here when members choose to share them."/>}</div>}

export function GuidelinesPage(){const sections=[["Respect every person","Treat the humans behind each avatar with patience, dignity, and care."],["Consent comes first","Ask before involving others, sharing content, or crossing personal boundaries."],["Keep the community safe","No harassment, hate, threats, doxxing, scams, or deliberately harmful behavior."],["Protect private conversations","Messages and personal details stay private unless everyone involved agrees otherwise."],["Build in good faith","Ideas, collaborations, and meetups should be honest, constructive, and community-minded."],["Ask for help early","If something feels wrong, contact the Captain rather than escalating it yourself."]];return <div className="page"><PageHeader eyebrow="Community guidelines" title="A kind, safe orbit" description="The short version: respect boundaries, protect each other, and leave the community better than you found it."/><div className="guideline-hero panel"><Sparkles/><div><h2>We make this space together</h2><p>Every member shapes the tone of the community. These standards apply everywhere in the app.</p></div></div><div className="guidelines-grid">{sections.map(([title,body],i)=><article className="panel guideline" key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div>}

export function MeetupsPage({user,profile}){const{data,loading,error,reload}=useLoader(getMeetups,[]);const[open,setOpen]=useState(false);const mine=(data||[]).filter(m=>m.user_id===user.id);return <div className="page"><PageHeader eyebrow="Meetup calendar" title="Plan time together" description="Request VRChat hangouts and keep your upcoming community plans in one place." action={<button className="button primary" onClick={()=>setOpen(true)}><CalendarDays/>Request meetup</button>}/>{loading?<Loading/>:error?<ErrorState message={error} retry={reload}/>:mine.length?<div className="timeline">{mine.map(item=><article className="panel meetup-card" key={item.id}><div className="date-tile"><strong>{new Date(item.meetup_date+"T00:00:00").getDate()}</strong><span>{new Intl.DateTimeFormat(undefined,{month:"short"}).format(new Date(item.meetup_date+"T00:00:00"))}</span></div><div><div className="card-meta"><span className={`status ${item.status}`}>{item.status}</span><span>{item.start_time} · {item.duration} min</span></div><h3>{item.meetup_type}</h3><p>{item.message}</p></div></article>)}</div>:<Empty title="No meetups requested" body="Choose a date and send the Captain a meetup request."/>}{open&&<SubmitModal kind="meetup" user={user} profile={profile} onClose={()=>setOpen(false)} onSaved={reload}/>}</div>}

export function SupportPage({profile}){const{data,loading}=useLoader(getSupporters,[]);const[busy,setBusy]=useState("");const tiers=[{id:"cadet",name:"Cadet",price:"$2.99",features:["Supporter badge","Name on supporter wall"]},{id:"crewmate",name:"Crewmate",price:"$5.99",features:["Everything in Cadet","Custom profile theme"]},{id:"officer",name:"Officer",price:"$9.99",features:["Everything in Crewmate","Officer recognition"]}];async function checkout(tier){setBusy(tier);try{window.desktop.openExternal(await startSupportCheckout(tier,profile.username))}finally{setBusy("")}}return <div className="page"><PageHeader eyebrow="Support the Captain" title="Fuel the next mission" description="Optional monthly support helps keep the community, events, and projects moving."/><div className="tier-grid">{tiers.map((tier,i)=><article className={`panel tier-card ${i===1?"featured":""}`} key={tier.id}>{i===1&&<span className="recommended">Most popular</span>}<Heart/><h2>{tier.name}</h2><div className="price">{tier.price}<small>/ month</small></div><ul>{tier.features.map(f=><li key={f}><Check/>{f}</li>)}</ul><button className="button primary wide" disabled={busy===tier.id} onClick={()=>checkout(tier.id)}>{busy===tier.id?"Opening…":`Choose ${tier.name}`}</button></article>)}</div><section className="supporters"><h2>Current supporters</h2>{loading?<Loading/>:<div className="supporter-row">{data?.map(p=><div className="supporter-chip" key={p.username}><Avatar profile={p} size={34}/><span>{p.username}<small>{p.support_tier}</small></span></div>)}</div>}</section></div>}

export function ProfilePage({user,profile,onUpdated}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");async function save(event){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);try{let avatar=profile.avatar;const file=f.get("avatar");if(file?.size)avatar=await uploadAvatar(user.id,file);const next=await updateProfile(user.id,{username:f.get("username"),favorite_game:f.get("favorite_game"),birthday:f.get("birthday")||null,show_birthday:f.get("show_birthday")==="on",discord:f.get("discord"),youtube:f.get("youtube"),twitch:f.get("twitch"),vrchat:f.get("vrchat"),steam:f.get("steam"),bio:f.get("bio"),avatar});onUpdated(next);setMessage("Profile saved.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}return <div className="page"><PageHeader eyebrow="Your profile" title="Your crew identity" description="Control how you appear throughout the community."/><form className="panel profile-form" onSubmit={save}><div className="profile-preview"><Avatar profile={profile} size={96}/><div><h2>{profile.username}</h2><span className="rank">{profile.rank||"Crew"}</span></div></div><div className="form-grid"><Field label="Username"><input name="username" defaultValue={profile.username} required/></Field><Field label="Favorite game"><input name="favorite_game" defaultValue={profile.favorite_game}/></Field><Field label="Birthday"><input name="birthday" type="date" defaultValue={profile.birthday||""}/></Field><Field label="Avatar"><input name="avatar" type="file" accept="image/png,image/jpeg,image/webp,image/gif"/></Field><Field label="Discord"><input name="discord" defaultValue={profile.discord}/></Field><Field label="VRChat"><input name="vrchat" defaultValue={profile.vrchat}/></Field><Field label="Steam"><input name="steam" defaultValue={profile.steam}/></Field><Field label="YouTube"><input name="youtube" defaultValue={profile.youtube}/></Field><Field label="Twitch"><input name="twitch" defaultValue={profile.twitch}/></Field></div><Field label="Bio"><textarea name="bio" rows="5" defaultValue={profile.bio}/></Field><label className="check-field"><input name="show_birthday" type="checkbox" defaultChecked={profile.show_birthday}/><span>Show my birthday to the community</span></label><div className="button-row"><button className="button primary" disabled={busy}>{busy?"Saving…":"Save profile"}</button>{message&&<span className="form-message inline">{message}</span>}</div></form></div>}
